<?php

/*
|--------------------------------------------------------------------------
| Products
|--------------------------------------------------------------------------
| Drives /products, /products/{slug} and the Products menu. Add a product
| here and it appears in the nav (grouped by 'category'), on the products
| page, in the sitemap and on its industry page.
|
| category     — heading it sits under in the Products menu
| industry     — slug in config/industries.php it belongs to
| shots        — images in public/images/products/{slug}/. The first is the
|                hero. 'frame' is browser (default), plain or phone.
| features     — [icon, title, body]
| flow         — [title, body] steps
| roles        — [icon, title, body]
| faqs         — [question, answer]
|
| Screens show demonstration data only. Never publish client data here.
*/

return [

    'e-memo' => [
        'name'            => 'E-Memo',
        'category'        => 'Government',
        'industry'        => 'government',
        'icon'            => 'forward_to_inbox',
        'blurb'           => 'Electronic memo registry',
        'tagline'         => 'The electronic memo registry',
        'address'         => 'memo.yourorganisation.gov.ng',
        'schema_category' => 'BusinessApplication',
        'description'     => 'E-Memo replaces paper memos in ministries, agencies and institutions. Draft on your letterhead, route through the proper chain of offices, and keep every minute, forward and read on the record.',
        'summary'         => 'Paper memos are slow, and once one leaves a desk nobody can say where it is. E-Memo puts the whole registry online: drafted on your letterhead, routed through the proper offices in order, numbered at dispatch and traceable to every reader.',
        'heading'         => 'Every memo numbered, routed',
        'accent'          => 'and accounted for.',
        'lead'            => 'E-Memo replaces paper memos inside ministries, agencies and institutions. Staff draft on the official letterhead, route through the proper chain of offices, and every minute, forward and read is recorded. Nothing waits unseen in a file tray, and nothing leaves the building untraced.',
        'proof'           => ['Runs in the browser, nothing to install', 'Your crest, letterhead and structure', 'Every action recorded against a name'],
        'stats'           => [
            ['3',    'kinds of correspondence: internal memos, external letters and circulars'],
            ['4',    'handling levels, from Public through to Secret'],
            ['4',    'letterhead designs, chosen for each kind of memo'],
            ['100%', 'of views, prints and downloads logged against a named reader'],
        ],
        'why' => [
            'heading' => 'Paper memos are slow,',
            'accent'  => 'and nobody can prove where they went.',
            'body'    => 'A memo that travels by hand depends on who is at their desk. It waits, it gets lost, and when it finally arrives nobody can show who held it or what they wrote on it. E-Memo keeps the formality of the registry and removes the waiting.',
            'before'  => [
                'Memos waiting in file trays while an officer is away',
                'No way to see which office a memo is sitting with',
                'Minutes written in margins and lost with the file',
                'Unnumbered correspondence that cannot be found later',
                'Confidential memos photocopied with no trace of who did it',
            ],
            'after' => [
                'Each office on the chain is notified the moment it is their turn',
                'A routing chain that shows who has it now and who is next',
                'Every minute kept in one thread, in order, with a name and time',
                'A reference number assigned at dispatch and never reused',
                'A personal tracking code watermarked on every copy a reader opens',
            ],
        ],
        'features_heading' => 'The whole registry,',
        'features_accent'  => 'without the file trays.',
        'features_note'    => 'Also included: memo templates with self-filling placeholders, distribution lists, cover and delegation for officers on leave, read receipts, and notifications by email and in the portal.',
        'features' => [
            ['route',           'Routing through the proper chain',  'Set the offices a memo must pass through. Each one acts strictly in order, forwarding it with a minute or returning it with a reason.'],
            ['tag',             'Automatic reference numbers',       'A number is assigned at dispatch from your prefix, the office code, the year and a counter. Numbers are locked and never reused.'],
            ['account_balance', 'Offices, not just people',          'An office is separate from whoever holds it. Appoint substantive or acting holders, and the office mailbox and history pass to the successor.'],
            ['forum',           'Minuting on the record',            'Comments, forwards and return reasons are merged into one chronological thread on the memo, each with a name and a time.'],
            ['campaign',        'Circulars addressed by rule',       'Send to everyone, to one part of the organisation and everything under it, to a grade-level range, or to a saved distribution list.'],
            ['draw',            'Signatures and letterhead',         'Sign on a pad or upload a signature. It is placed on the memo when you send, and the memo prints on your A4 letterhead.'],
            ['fingerprint',     'Leak protection',                   'Every reader has a personal tracking code, watermarked across each memo they open or print. Secret memos need a password and cannot be printed.'],
            ['auto_awesome',    'AI summary of unread memos',        'One click gives a digest of what is waiting, written out or read aloud. Confidential and Secret memos are never sent to the AI, and it can be switched off.'],
            ['history',         'An audit trail that cannot be edited', 'An append-only record of what was done in the portal and by whom, searchable by action, person and date.'],
        ],
        'shots' => [
            ['file' => 'dashboard.webp', 'title' => 'Dashboard'],
            ['file' => 'memo.webp', 'path' => '/memos', 'label' => 'Memo view',
             'title'  => 'The memo, its chain and its trail on one page',
             'body'   => 'Open a memo and everything about it is there: the memo on its letterhead, the offices it must pass through, who has read it and every minute written on it. If it is with you, you forward it or return it without leaving the page.',
             'points' => ['Letterhead, signature block and attachments', 'Forward with a minute, or return with a reason', 'Routing chain and read receipts alongside']],
            ['file' => 'compose.webp', 'path' => '/memos/compose', 'label' => 'Drafting',
             'title'  => 'Draft in your own name, or in the name of your office',
             'body'   => 'Write the memo in a proper editor, choose who it goes to and through, and set how it must be handled. Send as yourself or in the capacity of an office you hold, and preview it on the letterhead before it goes anywhere.',
             'points' => ['Internal memo, external letter or circular', 'Priority and confidentiality set per memo', 'Start from a template, and link other memos with #']],
            ['file' => 'settings.webp', 'path' => '/admin/settings', 'label' => 'Letterhead builder',
             'title'  => 'Your crest, your letterhead, your rules',
             'body'   => 'Upload your crest, set your name, address and motto, and choose a letterhead design for each kind of memo. A live preview shows the real sheet as you change it, so the first memo sent already looks official.',
             'points' => ['Four designs: Classic, Modern, Official and Minimal', 'Accent colour, typeface and footer note', 'Different letterheads for memos, letters and circulars']],
            ['file' => 'audit.webp', 'path' => '/admin/audit-logs', 'label' => 'Audit trail',
             'title'  => 'A record nobody can tidy up afterwards',
             'body'   => 'Every consequential action is written to a log that cannot be edited or removed, by anyone. It records that a memo was opened, not what it said, so the trail is safe to show an auditor.',
             'points' => ['Filter by action, person and date', 'Views, prints and attachment opens all recorded', 'Read-only, even for administrators']],
        ],
        'flow_heading' => 'From draft to file,',
        'flow_accent'  => 'on the record.',
        'flow' => [
            ['Draft',              'Compose on the letterhead, from a template if you like, and preview the sheet before it goes anywhere.'],
            ['Route',              'Each office on the chain forwards it with a minute or returns it with a reason, strictly in order.'],
            ['Dispatch',           'The last forward dispatches the memo. A reference number is assigned and every addressee is notified.'],
            ['Read, minute, file', 'Recipients read it with a receipt recorded, minute it, print it on letterhead and file it away.'],
        ],
        'roles' => [
            ['edit_note',            'Staff',          'Draft, receive, minute, forward and return memos, with templates and lists to speed up the routine ones.'],
            ['inventory_2',          'Registry',       'Draft and dispatch on behalf of officers, then file and track correspondence across the organisation.'],
            ['account_balance',      'Office holders', 'Act in the name of the office you hold, substantive or acting. Authority comes from the office, not the login.'],
            ['admin_panel_settings', 'Administrators', 'Manage staff accounts, the organisation structure, offices and holders, roles, and the letterhead.'],
        ],
        'outcomes' => [
            'A numbered, searchable record of every memo',
            'A visible chain showing who has it now',
            'Confidential memos that stay confidential',
            'Office history that survives a change of holder',
        ],
        'faqs' => [
            ['Can it follow our own structure and titles?', 'Yes. The organisation tree can be any depth, with levels you name yourself, whether that is department, division and unit or faculty and department. Offices have their own codes and reporting lines.'],
            ['What happens when an officer is on leave or is replaced?', 'An officer can arrange cover for a date range, and actions then show as one person acting for another. When a holder changes, the office mailbox and its history pass to the successor.'],
            ['How are confidential memos protected?', 'Each memo carries a handling level. Confidential and Secret memos are left out of general search and are never sent to the AI. Secret memos need a password to open, cannot be printed, and every copy carries the reader\'s tracking code.'],
            ['How do we get our staff onto it?', 'Staff are added one at a time or uploaded from a spreadsheet. Each receives an email with a single-use link to set a password, and is guided to add a photo and signature at first sign-in.'],
            ['Is the AI summary optional?', 'Yes. It can be switched off in settings for the whole organisation, and even when it is on, Confidential and Secret memos are never included.'],
        ],
        'cta_heading' => 'See a memo travel from desk to desk',
        'cta_accent'  => 'in under a minute.',
    ],

    'accountra' => [
        'name'            => 'Accountra',
        'category'        => 'Government',
        'industry'        => 'government',
        'icon'            => 'account_balance_wallet',
        'blurb'           => 'Public-sector accounting',
        'tagline'         => 'Public-sector accounting and Treasury payments',
        'address'         => 'accounts.yourorganisation.gov.ng',
        'schema_category' => 'FinanceApplication',
        'description'     => 'Accountra keeps the books of a ministry, agency, tertiary institution or local government council: Treasury vouchers, votebook, cashbook, budget control, approvals and IPSAS cash-basis statements in one system.',
        'summary'         => 'The votebook, the cashbook and the advance ledger were designed for paper, and paper cannot refuse an overspend. Accountra runs the whole Treasury payment cycle in one system, enforces the budget on every voucher and produces the statements auditors ask for.',
        'heading'         => 'The Treasury books,',
        'accent'          => 'kept by the system.',
        'lead'            => 'Accountra keeps the books of a ministry, agency, tertiary institution or local government council. It follows the Treasury payment cycle from the moment a voucher is raised to the moment cash leaves the bank, enforces the budget along the way, and produces the registers, ledgers and IPSAS cash-basis statements that go with it.',
        'proof'           => ['Built around Nigerian Treasury practice', 'Budget enforced at the point of entry', 'IPSAS cash-basis statements'],
        'stats'           => [
            ['4',         'kinds of organisation it adapts to: ministries, agencies, tertiary institutions and councils'],
            ['3',         'approval stages: checked, audited and approved, with limits by role'],
            ['T27 · TF1', 'Treasury voucher forms, with deductions worked out for you'],
            ['IPSAS',     'cash-basis financial statements, drawn straight from the ledger'],
        ],
        'why' => [
            'heading' => 'A paper votebook cannot',
            'accent'  => 'refuse an overspend.',
            'body'    => 'The Treasury books were designed for paper, and paper records what happened after it happened. By the time the votebook shows a vote is exhausted, the voucher has been raised, approved and paid. Accountra checks the budget before the voucher exists.',
            'before'  => [
                'Vouchers raised against votes that are already exhausted',
                'VAT, withholding tax and stamp duty worked out by hand',
                'A cashbook, votebook and ledger that never quite agree',
                'Deductions remitted late because nobody totalled them',
                'Month-end reports rebuilt from several books each time',
            ],
            'after' => [
                'A voucher that would exceed its budget line is refused',
                'Deductions computed as the voucher is typed, each with its own breakdown voucher',
                'One cashbook entry posts the general ledger automatically',
                'Outstanding deductions gathered into schedules ready to remit',
                'Trial balance and statements available on any day of the year',
            ],
        ],
        'features_heading' => 'The full payment cycle,',
        'features_accent'  => 'in one set of books.',
        'features_note'    => 'Also included: revenue receipts, imprest, deposits, contracts and commitments, grants, funds and cost centres, an audit trail, nightly backups, bulk import and a read-only API.',
        'features' => [
            ['receipt_long',    'Treasury payment vouchers',     'Raise T27 contractor vouchers, TF1 payment vouchers and staff advances. PV numbers are generated, amounts are put into words, and everything prints to PDF.'],
            ['calculate',       'Deductions worked out for you', 'VAT, withholding tax, stamp duty and admin charges are computed on entry, then gathered into schedules to remit with the revenue reference.'],
            ['gpp_good',        'Hard budget control',           'One budget per year by account and sub-head, with supplementary appropriations, virements and warrants. A voucher that exceeds its line is refused.'],
            ['approval',        'Multi-stage approvals',         'Checked, audited, approved, in that order. Titles follow your organisation, each stage can carry an amount limit, and a returned document comes back with a comment.'],
            ['menu_book',       'Votebook and cashbook',         'A vote ledger for each account and year, and the Treasury Cashbook with receipts and payments sides, brought forward each month.'],
            ['account_tree',    'A ledger that posts itself',    'Every cashbook line posts a balanced cash-basis journal. The trial balance shows at a glance whether the books agree with the cashbook.'],
            ['sync_alt',        'Bank reconciliation',           'Import the bank statement from CSV or Excel. Lines are matched to the cashbook automatically, and the month-end reconciliation statement prints.'],
            ['summarize',       'IPSAS financial statements',    'The Statement of Receipts and Payments and the Statement of Assets and Liabilities, by account or by fund, exported to Excel.'],
            ['groups',          'Payroll, stores and assets',    'Payroll with PAYE, pension, NHF and NHIS for organisations not on IPPIS, store receipt and issue vouchers, and a tagged fixed asset register.'],
        ],
        'shots' => [
            ['file' => 'dashboard.webp', 'title' => 'Dashboard'],
            ['file' => 'approvals.webp', 'path' => '/approvals', 'label' => 'Approvals',
             'title'  => 'Checked, audited and approved, in that order',
             'body'   => 'Every voucher follows the chain your organisation actually uses, with the right title at each stage. The approver sees the document, its supporting files and exactly what it does to the budget line before deciding.',
             'points' => ['Titles follow your organisation, from Bursar to Permanent Secretary', 'Amount limits by role at each stage', 'Return a document with a comment instead of rejecting it outright']],
            ['file' => 'voucher.webp', 'path' => '/voucher/register', 'label' => 'Voucher entry',
             'title'  => 'Deductions worked out as you type',
             'body'   => 'Enter the gross and the payment type and the system does the rest: VAT, withholding tax, stamp duty and admin charges, the net payable and the amount in words. Each deduction gets its own breakdown voucher.',
             'points' => ['Head and sub-head from the National Chart of Accounts', 'Budget line checked before the voucher is saved', 'Deductions queued for the remittance schedule']],
            ['file' => 'budget.webp', 'path' => '/reports/budget-performance', 'label' => 'Budget performance',
             'title'  => 'Know what is left on every line, today',
             'body'   => 'Approved, revised, released, charged, committed and available, for every account and every sub-head. The report is drawn from the same entries as the votebook, so it is never a month behind.',
             'points' => ['Supplementary appropriations and virements shown', 'Commitments from contracts counted against the line', 'Print, or export to Excel']],
        ],
        'flow_heading' => 'From release to report,',
        'flow_accent'  => 'one entry at a time.',
        'flow' => [
            ['Record the release',   'Record the allocation or release. The votebook gets its balance and the month\'s cashbook opens.'],
            ['Raise the voucher',    'The budget line is checked as the voucher is raised, and deductions are worked out on entry.'],
            ['Approve it',           'The voucher is checked, audited and approved by the right officers, each within their limit.'],
            ['Pay, post and report', 'Pay by mandate or cheque. The cashbook entry posts the ledger, and the statements are already up to date.'],
        ],
        'roles' => [
            ['edit_document',   'Accounts officers',  'Raise vouchers and advances, record retirements and attach supporting documents.'],
            ['fact_check',      'Heads of accounts',  'Check vouchers, manage the budget and remittances, and reconcile the bank. Bursar or Treasurer where that is the title.'],
            ['policy',          'Internal auditors',  'Audit every voucher before payment, with the audit trail and attachments to hand.'],
            ['verified_user',   'Approving officers', 'Give final approval within your limit, and see the position of every account from the dashboard.'],
        ],
        'outcomes' => [
            'Spending that cannot exceed the budget line',
            'Books that agree with each other every day',
            'Deductions remitted on schedule, with references',
            'Statements ready for audit without a rebuild',
        ],
        'faqs' => [
            ['Does it follow Nigerian Treasury practice?', 'Yes. It uses the T27 and TF1 voucher forms, the votebook and the Treasury Cashbook, loads the National Chart of Accounts for the federal, state or local tier, and produces IPSAS cash-basis statements.'],
            ['We are a university or a council, not a ministry. Will it fit?', 'Yes. It is set up for one of four kinds of organisation, and the titles, forms and approval chain follow that choice: Bursar and Vice-Chancellor for an institution, Treasurer and Chairman for a council.'],
            ['Can we bring our existing records across?', 'Yes. Contractors, staff, opening balances, assets, stock and paid-voucher history can be imported from spreadsheets. Every import is previewed before anything is saved.'],
            ['We are on IPPIS and GIFMIS. Does that change anything?', 'It does, and the system accounts for it. Payroll is for organisations that are not on IPPIS. With GIFMIS switched on, payments are batched into mandates with an e-payment schedule. Without it, there is a cheque register.'],
            ['Can other systems read our figures?', 'Yes. A read-only API covers vouchers, the cashbook, the trial balance, budget performance and more, using tokens you issue and can revoke.'],
        ],
        'cta_heading' => 'Bring one month of vouchers and',
        'cta_accent'  => 'watch the books keep themselves.',
    ],

    'kolect' => [
        'name'            => 'Kolect',
        'category'        => 'Education',
        'industry'        => 'education',
        'icon'            => 'forum',
        'blurb'           => 'Student payments by chat',
        'tagline'         => 'Every student payment, paid from a chat',
        'address'         => 'kolect.online',
        'schema_category' => 'FinanceApplication',
        'description'     => 'Kolect collects faculty and departmental dues, SUG dues, handbooks and fees for universities, polytechnics and colleges. Students pay on WhatsApp, Telegram, the web or USSD, and money settles straight to the unit that owns the charge.',
        'summary'         => 'Dues collected in cash are dues nobody can trace. Kolect lets students pay from the chat app already on their phone, splits each payment at source, and settles it straight into the account of the faculty, department or union that raised the charge.',
        'heading'         => 'Every student payment,',
        'accent'          => 'paid from a chat.',
        'lead'            => 'Kolect collects faculty and departmental dues, SUG dues, handbooks, lab fees and levies for universities, polytechnics and colleges. Students pay on WhatsApp or Telegram, in a browser or by USSD, and the money settles straight into the account of the unit that owns the charge. Kolect never holds it.',
        'proof'           => ['Nothing for students to install', 'Money settles direct to each unit', 'Receipts anyone can verify'],
        'stats'           => [
            ['4',     'ways to pay: WhatsApp, Telegram, the web and USSD'],
            ['3',     'payment gateways supported: Credo, Monnify and Paystack'],
            ['₦0',    'held by Kolect. Every payment is split at source to the unit'],
            ['07:00', 'daily digest to every officer, sent even on a quiet day'],
        ],
        'why' => [
            'heading' => 'Dues collected in cash',
            'accent'  => 'are dues nobody can trace.',
            'body'    => 'Departmental dues, faculty dues and union levies are still collected by hand on many campuses, or paid into one account and shared out later. Students queue, receipts get forged, and no unit is sure what it is owed. Kolect removes the cash and the sharing formula.',
            'before'  => [
                'Cash and bank tellers collected by class representatives',
                'Money pooled in one account, then shared out by hand',
                'Receipts that nobody can check are genuine',
                'Students charged twice, or not charged at all',
                'Officers who can see every unit\'s figures, or none',
            ],
            'after' => [
                'Students pay from the chat app already on their phone',
                'Each payment is split at source and settled to the unit that owns it',
                'Every receipt carries a code and QR that anyone can verify',
                'What a student owes is worked out live from the roster and past payments',
                'Each officer sees their own unit, and only their own unit',
            ],
        ],
        'features_heading' => 'Collection, settlement and proof,',
        'features_accent'  => 'without the cash.',
        'features_note'    => 'Also included: clearance slips, academic sessions with promotion and graduation, scheduled exports by email, gateway health, an audit log and custom domains for each school.',
        'features' => [
            ['chat',                 'Pay on WhatsApp or Telegram',  'A bot carrying your school\'s own name and crest. A student gives a matric number and the last four digits of their phone, sees what they owe and pays.'],
            ['language',             'Web and USSD as well',         'The same flow runs in a browser with no account, for the business centre. USSD works on any phone and needs no internet.'],
            ['call_split',           'Settled at source',            'The gateway splits each payment the moment it is made. Departmental dues land in the department\'s account, union dues in the union\'s.'],
            ['verified',             'Receipts that can be checked', 'PDF and image receipts with a verification code and QR, sent in the chat and by email. Anyone holding one can confirm it without an account.'],
            ['shield_person',        'Scoped by design',             'A departmental officer sees their department, a faculty officer their faculty. Exports and reports respect the same boundary.'],
            ['fact_check',           'Verified, never double-counted', 'Every payment is confirmed against the gateway\'s own records before it counts, and stale payments are re-checked automatically.'],
            ['upload_file',          'Rosters from a spreadsheet',   'Each unit uploads its own student list. A student on both a department and a faculty roster becomes one record, billed by each.'],
            ['notifications_active', 'Reminders and digests',        'Send reminders to students who still owe a charge, by chat or email. Every officer gets a morning summary of the previous day.'],
            ['api',                  'Ledger, settlements and API',  'A filterable payments ledger with Excel and PDF export, payouts matched to collections, and a read-only API for the bursary system.'],
        ],
        'shots' => [
            ['file' => 'landing.webp', 'title' => 'Kolect'],
            ['file' => 'chat.webp', 'frame' => 'phone', 'label' => 'For students',
             'title'  => 'Dues paid in the chat they already use',
             'body'   => 'No app, no account, no password. A student opens the school\'s bot, proves who they are with two things only they and the roster know, sees exactly what they owe and pays. The receipt arrives in the same chat.',
             'points' => ['Identified by matric number and phone digits', 'Only charges that apply to that student are shown', 'Receipt sent in chat and by email']],
            ['file' => 'flowgrid.webp', 'frame' => 'wide', 'label' => 'Where the money goes',
             'title'  => 'Straight to the unit that owns the charge',
             'body'   => 'Nothing pools in a central account waiting to be shared out. Each unit that collects has its own bank account on the system, and the gateway routes every payment there at the moment it is made.',
             'points' => ['Faculties, departments, unions and hostels each settle separately', 'Every payment verified by amount, currency and reference', 'Payouts matched back to collections automatically']],
            ['file' => 'officer.webp', 'frame' => 'plain', 'label' => 'For officers',
             'title'  => 'Every officer sees their own unit. Only their own unit.',
             'body'   => 'Each unit\'s officer gets a portal showing what their unit has collected, who has paid and who has not. They cannot see another unit\'s figures, and nothing they export can cross that line.',
             'points' => ['Collected, students and paid-up rate at a glance', 'Payments with status, searchable by matric or surname', 'A morning digest, so silence always means something is wrong']],
            ['file' => 'receipt.webp', 'frame' => 'phone', 'label' => 'Receipts',
             'title'  => 'A receipt nobody can fake',
             'body'   => 'Every receipt has its own number, a verification code and a QR. A lecturer, a clearance officer or a parent can scan it or type the code at the school\'s address and see at once whether it is genuine.',
             'points' => ['Amount in figures and in words', 'Verification open to anyone, with no login', 'Clearance slips issued from the same record']],
        ],
        'flow_heading' => 'Live in a few steps,',
        'flow_accent'  => 'collecting the same week.',
        'flow' => [
            ['Set up the school',       'We create your school at its own address and add every unit that collects, each with its own bank account.'],
            ['Upload rosters',          'Each unit uploads its student list and sets its charges: every session, every semester or one-off.'],
            ['Students pay in chat',    'A student opens the bot, proves who they are, sees what they owe and pays. A receipt arrives at once.'],
            ['Settle, verify, report',  'Money settles to each unit. Officers get a daily digest, and anyone can verify a receipt.'],
        ],
        'roles' => [
            ['school',          'Students',             'Pay from WhatsApp, Telegram, a browser or USSD with no account, and get a receipt and clearance slip.'],
            ['badge',           'Unit officers',        'Manage your unit\'s charges and roster, follow payments and settlements, and send reminders.'],
            ['account_balance', 'The bursary',          'Run the whole school: units, charges, officers, sessions, settlements, exports and the audit log.'],
            ['integration_instructions', 'Your other systems', 'Pull payments into the bursary system through a read-only API with tokens the school issues.'],
        ],
        'outcomes' => [
            'Dues in the right account, with no sharing formula',
            'A live picture of who has paid and who has not',
            'Receipts that verify in seconds',
            'No cash handled by class representatives',
        ],
        'faqs' => [
            ['Does the money pass through Kolect?', 'No. The payment gateway splits each payment at source and settles it directly to the bank account of the unit that owns the charge. Kolect never holds funds.'],
            ['What can we collect with it?', 'Any institutional payment a unit raises: faculty and departmental dues, SUG dues, handbooks, lab fees, damage fees, and alumni or association levies.'],
            ['Do students need a smartphone?', 'No. Students without one can pay in a browser at a business centre with no account, or by USSD on any phone, with the receipt sent by email.'],
            ['Can a student be charged twice?', 'What a student owes is worked out from the roster, the charges and what they have already paid, so a paid charge is not offered again. Every payment is also verified with the gateway before it counts.'],
            ['How do we know a receipt is real?', 'Each receipt carries a verification code and a QR. Anyone can check it at the school\'s address without logging in, and staff have their own verification screen.'],
            ['What does it cost?', 'A flat service charge on each payment, shown to the student before they pay and itemised on the receipt, so the unit receives every naira it charged. Ask us for current rates.'],
        ],
        'cta_heading' => 'Tell us about your institution and',
        'cta_accent'  => 'we will set it up with you.',
        'cta_body'    => 'We create the school, connect the bank accounts and the bot, and bring your first units on board. You see the first payments settle before anyone has handled cash.',
    ],

];
